[package]
name = "lantern"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
songbird = { version = "0.3.2", features = ["driver"] }
toml = "0.7.3"
serde_derive = "1.0.160"
serde = "1.0.160"
tokio = { version = "1", features = ["full"] }
kafka = "0.9.0"
openssl = "0.10.52"
log = "0.4"
once_cell = "1.17.1"
humantime = "2.1.0"
nanoid = "0.4.0"
serde_json = "1.0.96"
hashbrown = "0.13.2"
futures = "0.3.28"
fern = { version = "0.6.2", features = ["colored"] }
reqwest = "0.11.17"
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"] }
webhook = "2.1.2"
flume = "0.10.14"