[package]
name = "lantern"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11.5"
toml = "0.7.3"
serde_derive = "1.0.160"
serde = "1.0.160"
tokio = { version = "1", features = ["full"] }
kafka = "0.9.0"
openssl = "0.10.52"
env_logger = "0.10.0"
once_cell = "1.17.1"
nanoid = "0.4.0"
serde_json = "1.0.96"
