[roles]
scheduler = true
worker = true

[config]
# Discord settings for user here in future token, etc...
workers = [
    "https://xxxxxxxxx1.internal.lanternsystems.com",
    "https://xxxxxxxxx2.internal.lanternsystems.com",
    "https://xxxxxxxxx3.internal.lanternsystems.com"
] # Something like this
# You don't have to add the internal worker inside of the scheduler (if configured) here
